---
# tasks file for docker-build

- name: Build Image {{image_name}}
  import_tasks: image-build.yml
  when: docker_push
- name: docker login 
  import_tasks: docker-login.yml
  when: docker_registry_login
- name: docker push {{image_name}}
  import_tasks: image-push.yml
  when: docker_push
- name: Docker build local {{image_name}}
  import_tasks: image-build_local.yml
  
