- hosts: localhost
  connection: local
  vars:
    #docker_registry_username: "{{ docker_registry_username }}"
    #docker_registry_password: "{{ docker_registry_password }}"
    docker_push: "{{ docker_push  }}"
    docker_registry_login: "{{ docker_push }}"
    image_version: "{{ image_version }}"
 


  roles:
    - role: docker-build
      image_name: "ngnix"
      docker_file_path: "./ngnix/"

    - role: docker-build
      image_name: "webapp"
      docker_file_path: "./webapp/"
  tasks: 
    - shell: docker images | grep -i "{{ image_version }}"
      register: output
    - debug:
        msg: "{{ output.stdout_lines }}"
