FROM tomcat:8.0.20-jre8
CMD [ cp -r ../assets/devopschallenge.war /usr/local/tomcat/webapps/ ] 


#RUN pwd
#
#WORKDIR /tmp
#RUN git clone https://${username}:${password}@bitbucket.org/wirecard_sre_recruitment/challenge.git
#CMD [ cp -f challenge/assets/devopschallenge.war /usr/local/tomcat/webapps/ ]

